# Generated by Django 6.1 on 2026-09-03 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Main promotional title (e.g., 'Summer Sale 2024')", max_length=200)),
                ('subtitle', models.CharField(blank=True, help_text="Secondary text/tagline (e.g., 'Up to 50% Off')", max_length=300, null=True)),
                ('image', models.ImageField(help_text='Desktop/main promotional image (recommended: 1200x400px)', upload_to='sliders/')),
                ('mobile_image', models.ImageField(blank=True, help_text='Optional mobile-optimized image (recommended: 600x400px)', null=True, upload_to='sliders/')),
                ('button_text', models.CharField(blank=True, help_text="Call-to-action button text (e.g., 'Shop Now')", max_length=100, null=True)),
                ('button_link', models.CharField(blank=True, help_text='Button destination URL (internal path or full URL)', max_length=500, null=True)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Display order on homepage (lower numbers show first)')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Only active sliders appear on homepage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Homepage Slider',
                'verbose_name_plural': 'Homepage Sliders',
                'ordering': ['display_order', 'created_at'],
                'indexes': [models.Index(fields=['is_active', 'display_order'], name='unyan_homes_is_acti_a4c7b3_idx')],
            },
        ),
    ]
