# Generated by Django 6.1 on 2026-08-31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_userprofile_is_phone_verified_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_owner",
            field=models.BooleanField(default=False),
        ),
    ]
