# Generated by Django 6.1 on 2026-09-03 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_is_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=140)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(help_text='Desktop/banner image', upload_to='sliders/')),
                ('mobile_image', models.ImageField(blank=True, help_text='Optional mobile image', null=True, upload_to='sliders/mobile/')),
                ('button_text', models.CharField(blank=True, max_length=64)),
                ('button_link', models.CharField(blank=True, help_text='Destination URL (internal or external)', max_length=1024)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', '-created_at'],
            },
        ),
    ]
