# Generated by Django 6.0.8 on 2026-09-12 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_homeslider'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='appearance',
            field=models.CharField(blank=True, default='system', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='language',
            field=models.CharField(blank=True, default='en', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notif_important',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notif_order_updates',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notif_promotions',
            field=models.BooleanField(default=False),
        ),
    ]
