# Generated by Django 6.1 on 2026-08-16 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vip', '0004_create_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountPopup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='popups/')),
                ('button_text', models.CharField(blank=True, max_length=80)),
                ('button_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Account Popup',
                'verbose_name_plural': 'Account Popups',
            },
        ),
    ]
