# Generated by Django 6.1 on 2026-09-15 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_flash_sale_end_product_flash_sale_start_and_more'),
        ('sellers', '0004_shopkeeper_store_deliveryworker_deliveryassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='sellers.store'),
        ),
    ]
