# Generated by Django 6.1 on 2026-09-16 04:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orderitem_fulfillment_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancellation_comment',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='order',
            name='cancellation_reason',
            field=models.CharField(blank=True, choices=[('ORDERED_BY_MISTAKE', 'I ordered by mistake'), ('NOT_NEEDED', "I don't need the product anymore"), ('BETTER_PRICE', 'I found a better price elsewhere'), ('DELIVERY_DELAY', 'Delivery is taking too long'), ('CHANGE_ADDRESS', 'I want to change my delivery address'), ('CHANGE_MOBILE', 'I want to change my mobile number'), ('WRONG_PRODUCT_QUANTITY', 'I ordered the wrong product or quantity'), ('PAYMENT_ISSUE', 'Payment issue'), ('NO_LONGER_REQUIRED', 'Product is no longer required'), ('OTHER', 'Other reason')], max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
