# Generated by Django 6.1 on 2026-08-31 20:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0002_sellerapplication_activation_completed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerpasswordchangeevent',
            name='changed_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
