# Generated by Django 6.1 on 2026-09-15 18:21

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0004_shopkeeper_store_deliveryworker_deliveryassignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryassignment',
            name='status',
            field=models.CharField(choices=[('assigned', 'Assigned'), ('accepted', 'Accepted'), ('picked_up', 'Picked Up'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('delayed', 'Delayed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='assigned', max_length=30),
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField(blank=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['city', 'name'],
                'indexes': [models.Index(fields=['city', 'state', 'is_active'], name='sellers_are_city_52921b_idx')],
            },
        ),
        migrations.AddField(
            model_name='deliveryworker',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_workers', to='sellers.area'),
        ),
        migrations.AddField(
            model_name='store',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stores', to='sellers.area'),
        ),
        migrations.CreateModel(
            name='DeliveryIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('incident_type', models.CharField(choices=[('road_blocked', 'Road Blocked'), ('accident', 'Accident'), ('waterlogging', 'Waterlogging/Flood'), ('traffic', 'Traffic'), ('vehicle_problem', 'Vehicle Problem'), ('weather_problem', 'Weather Problem'), ('safety_problem', 'Safety Problem'), ('other', 'Other')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('status', models.CharField(choices=[('reported', 'Reported'), ('acknowledged', 'Acknowledged'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], default='reported', max_length=20)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidents', to='sellers.area')),
                ('delivery_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='sellers.deliveryassignment')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reported_incidents', to='sellers.deliveryworker')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['area', 'status'], name='sellers_del_area_id_955e20_idx'), models.Index(fields=['severity', 'created_at'], name='sellers_del_severit_da6613_idx')],
            },
        ),
        migrations.CreateModel(
            name='RouteIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('issue_type', models.CharField(choices=[('road_closed', 'Road Closed'), ('bad_road', 'Bad Road'), ('heavy_traffic', 'Heavy Traffic'), ('construction', 'Construction'), ('waterlogging', 'Waterlogging'), ('accident', 'Accident'), ('unsafe_route', 'Unsafe Route'), ('weather', 'Weather'), ('other', 'Other')], max_length=30)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('monitoring', 'Monitoring'), ('resolved', 'Resolved'), ('expired', 'Expired')], default='active', max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expected_end_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='route_issues', to='sellers.area')),
                ('delivery_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='route_issues', to='sellers.deliveryassignment')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_route_issues', to='sellers.deliveryworker')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['area', 'status'], name='sellers_rou_area_id_2bffcf_idx'), models.Index(fields=['severity', 'created_at'], name='sellers_rou_severit_bbf569_idx')],
            },
        ),
    ]
