# Generated by Django 6.0.8 on 2026-09-22 07:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disputes', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dispute',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dispute',
            name='evidence',
            field=models.FileField(blank=True, null=True, upload_to='disputes/evidence/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='dispute',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('UNDER_REVIEW', 'Under review'), ('WAITING_BUYER', 'Waiting for buyer'), ('WAITING_SELLER', 'Waiting for seller'), ('RESOLVED_REFUND', 'Resolved with refund'), ('RESOLVED_RELEASE', 'Resolved with release'), ('REJECTED', 'Rejected'), ('CLOSED', 'Closed')], default='OPEN', max_length=20),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(max_length=20)),
                ('target_id', models.PositiveBigIntegerField()),
                ('reason', models.CharField(max_length=40)),
                ('description', models.TextField()),
                ('evidence', models.FileField(blank=True, null=True, upload_to='reports/evidence/%Y/%m/')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('INVESTIGATING', 'Investigating'), ('ACTION_REQUIRED', 'Action required'), ('RESOLVED', 'Resolved'), ('DISMISSED', 'Dismissed')], default='OPEN', max_length=20)),
                ('resolution', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('moderator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='moderated_reports', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports_made', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
