# Generated by Django 6.0.8 on 2026-09-22 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_feeconfiguration_compliancecheck_settlement'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='provider_order_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
