# Generated by Django 6.0.8 on 2026-09-22 06:40

import django.db.models.deletion
import payments.models
import uuid
from django.conf import settings
from django.db import migrations, models


def populate_order_ids(apps, schema_editor):
    Order = apps.get_model("payments", "Order")
    used_ids = set(Order.objects.exclude(order_id__isnull=True).values_list("order_id", flat=True))
    for order in Order.objects.filter(order_id__isnull=True).iterator():
        order_id = f"ORD-{uuid.uuid4().hex[:8].upper()}"
        while order_id in used_ids:
            order_id = f"ORD-{uuid.uuid4().hex[:8].upper()}"
        used_ids.add(order_id)
        Order.objects.filter(pk=order.pk).update(order_id=order_id)


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_listing_image'),
        ('payments', '0003_payment_provider_order_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('AWAITING_SELLER', 'Awaiting seller transfer'), ('TRANSFERRED', 'Transferred'), ('RECEIVED', 'Received')], default='AWAITING_SELLER', max_length=20)),
                ('seller_transferred_at', models.DateTimeField(blank=True, null=True)),
                ('buyer_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('transfer_note', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.CharField(editable=False, max_length=12, null=True),
        ),
        migrations.RunPython(
            code=populate_order_ids,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default=payments.models._order_id, editable=False, max_length=12, unique=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('PENDING_PAYMENT', 'PAID', 'IN_ESCROW', 'COMPLETED', 'DISPUTED'))), fields=('listing',), name='one_active_order_per_listing'),
        ),
        migrations.AddField(
            model_name='accounttransfer',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='transfer', to='payments.order'),
        ),
    ]
