# Generated by Django 6.0.8 on 2026-09-22 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_accounttransfer_order_order_id_order_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounttransfer',
            name='handoff_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accounttransfer',
            name='status',
            field=models.CharField(choices=[('AWAITING_SELLER', 'Awaiting seller transfer'), ('STARTED', 'Handoff in progress'), ('TRANSFERRED', 'Transferred'), ('RECEIVED', 'Received')], default='AWAITING_SELLER', max_length=20),
        ),
        migrations.AlterField(
            model_name='settlement',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('HELD', 'Held'), ('ELIGIBLE', 'Eligible'), ('PROCESSING', 'Processing'), ('PAID', 'Paid'), ('FAILED', 'Failed')], default='PENDING', max_length=10),
        ),
    ]
