# Generated by Django 6.1.1 on 2026-09-22 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_accounttransfer_handoff_started_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='listing_category',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='listing_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='listing_public_details',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='order',
            name='listing_title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
