# Generated by Django 6.0.8 on 2026-09-21 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('game_name', models.CharField(max_length=100)),
                ('entry_type', models.CharField(choices=[('free', 'Free'), ('paid', 'Paid')], max_length=20)),
                ('entry_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('prize_pool', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('max_players', models.PositiveIntegerField()),
                ('start_time', models.DateTimeField()),
                ('status', models.CharField(default='draft', max_length=30)),
            ],
        ),
    ]
