# Generated by Django 6.0.8 on 2026-09-11 18:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0004_orderitem_fulfillment_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MysteryRewardConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True)),
                ('claim_expiry_days', models.PositiveIntegerField(default=7)),
                ('display_title', models.CharField(default='Daily Mystery Reward Box', max_length=120)),
                ('display_subtitle', models.CharField(default='Open once per day and claim a surprise reward.', max_length=255)),
                ('button_label', models.CharField(default='Open Mystery Box', max_length=80)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mystery Reward Box Config',
                'verbose_name_plural': 'Mystery Reward Box Config',
            },
        ),
        migrations.CreateModel(
            name='MysteryRewardType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('reward_kind', models.CharField(choices=[('amount_off', 'Amount Off'), ('percent_off', 'Percent Off'), ('free_delivery', 'Free Delivery')], max_length=20)),
                ('amount_off', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('percent_off', models.PositiveIntegerField(default=0)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('weight', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', 'name'],
                'constraints': [models.CheckConstraint(condition=models.Q(('reward_kind', 'free_delivery'), ('amount_off__gte', 0), ('percent_off__gte', 0), _connector='OR'), name='rewards_valid_kind_values')],
            },
        ),
        migrations.CreateModel(
            name='MysteryRewardClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_code', models.CharField(db_index=True, max_length=32, unique=True)),
                ('claimed_date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('claimed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('is_used', models.BooleanField(db_index=True, default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('used_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mystery_reward_claims', to='orders.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mystery_reward_claims', to=settings.AUTH_USER_MODEL)),
                ('reward_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='rewards.mysteryrewardtype')),
            ],
            options={
                'ordering': ['-claimed_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'claimed_date'), name='uniq_daily_mystery_reward_claim')],
            },
        ),
    ]
